name: Publish Docker images

on: [repository_dispatch]

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseimage: [oracle/graalvm-ce:19.3.1-java8]
        minecraft_jar: [paper-1.15.2]
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker image to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.12
        env:
          BASEIMAGE: ${{ matrix.baseimage }}
          MINECRAFT_JAR: ${{ matrix.minecraft_jar }}.jar
        with:
          name: magikcraft/minecraft
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: ${{ matrix.minecraft_jar }}
  triggerDependentFlow:
    runs-on: ubuntu-latest
    needs: buildAndPublish
    steps:
      - continue-on-error: false
      - name: Tell Camunda Cloud What's up!
        uses: jwulf/zeebe-action@master
        with:
          zeebe_address: ${{ secrets.ZEEBE_ADDRESS }}
          zeebe_client_id: ${{ secrets.ZEEBE_CLIENT_ID }}
          zeebe_authorization_server_url: ${{ secrets.ZEEBE_AUTHORIZATION_SERVER_URL }}
          zeebe_client_secret: ${{ secrets.ZEEBE_CLIENT_SECRET }}
          operation: publishMessage
          message_name: BASE_IMAGE_REBUILT
          correlationKey: ${{ github.event.client_payload.buildid }}
