name: Publish Docker images

on: [repository_dispatch]

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker image to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: magikcraft/minecraft
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: "paper-1.15.2-graalvm"
      - name: Tell Camunda Cloud What's up!
        uses: jwulf/zeebe-action@master
        with:
          operation: publishMessage
          message_name: BASE_IMAGE_REBUILT
          variables: '{"buildid": "${{ github.event.client_payload.buildid }}"}'
