name: Kick off Build Orchestration

on: [push]
  branches: "master"
  
jobs:

  startWorkflow:

    runs-on: ubuntu-latest

    steps:
    - name: Create Zeebe Workflow
        uses: jwulf/zeebe-action@master
        with:
          zeebe_address: ${{ secrets.ZEEBE_ADDRESS }}
          zeebe_client_id: ${{ secrets.ZEEBE_CLIENT_ID }}
          zeebe_authorization_server_url: ${{ secrets.ZEEBE_AUTHORIZATION_SERVER_URL }}
          zeebe_client_secret: ${{ secrets.ZEEBE_CLIENT_SECRET }}
          operation: createWorkflowInstance
          bpmnProcessId: magikcraft-github-build
          variables: '{"buildid": "${{ github.sha }}-${{ time }}" }'
